# -*- coding: utf-8 -*-
"""
Created on Wed Feb  3 16:22:49 2021

@author: Bosa
"""
import os
import sys
import time
from controller import Controller

def retrieveFiles(reportFolder):
    """
    Parameters
    ----------
    reportFolder : It is the folder where report files generated by Bash script
    are, these files are in the following order and name:

        C:/someFolder/FilesInMain1.txt
        C:/someFolder/FilesInMain2.txt
        C:/someFolder/FilesInMainGit1.txt
        C:/someFolder/FilesInMainGit2.txt
        C:/someFolder/GitLog1.txt
        C:/someFolder/GitLog2.txt

    Returns
    -------
    updatedList : A list containing full file paths given above

    """
    fileList = os.listdir(reportFolder)
    updatedList = [(reportFolder + item) for item in fileList]
    return updatedList

if __name__ == "__main__":
    """
    FOLDER 1 = first folder to be synchronized
    FOLDER 2 = second folder to be synchronized
    FOLDER 3 = temprory folder created by Bash script
    """
    FOLDER1 = sys.argv[1]
    FOLDER2 = sys.argv[2]
    FOLDER3 = sys.argv[3]

    FILES = retrieveFiles(FOLDER3)
    CONTROLLER = Controller(FOLDER1, FOLDER2, FILES)
    time.sleep(1)
    print("Python: Waiting for a second")
    sys.exit()
